# Generated by Django 5.1 on 2024-08-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
    ]
